export type MuhammadNameSeed = {
  transliteration: string;
  meaning: string;
};

export const MUHAMMAD_99_NAMES: MuhammadNameSeed[] = [
  { transliteration: 'Aadil', meaning: 'The Just' },
  { transliteration: 'Aalim', meaning: 'The Scholar' },
  { transliteration: 'Abdullah', meaning: 'Servant of Allah' },
  { transliteration: 'Abu al Qaasim', meaning: 'Father of Qasim' },
  { transliteration: 'Abu at Tahir', meaning: 'Father of Tahir' },
  { transliteration: 'Abu at Tayyib', meaning: 'Father of Tayyib' },
  { transliteration: 'Abu Ibrahim', meaning: 'Father of Ibrahim' },
  { transliteration: 'Afoow', meaning: 'Forgiver' },
  { transliteration: 'Aheed', meaning: 'One who inclines to one side' },
  { transliteration: 'Ahmad', meaning: 'Most Praised' },
  { transliteration: 'Ajeer', meaning: 'One who is rewarded' },
  { transliteration: 'Alam ul Eeman', meaning: 'Banner of Faith' },
  { transliteration: 'Alam ul Yaqeen', meaning: 'Banner of Certainty' },
  { transliteration: 'Alamul Hudaa', meaning: 'Banner of Guidance' },
  { transliteration: 'Aleem', meaning: 'Knowledgeable' },
  { transliteration: 'Ameen', meaning: 'Trustworthy' },
  { transliteration: 'An Najm-us-Saqib', meaning: 'Shining Star' },
  { transliteration: 'Aqib', meaning: 'The Last' },
  { transliteration: 'Arabi', meaning: 'The Arab' },
  { transliteration: 'Awwal', meaning: 'The First' },
  { transliteration: 'Ayn ul Ghurr', meaning: 'Chief of the Chosen' },
  { transliteration: 'Ayn un Naeem', meaning: 'Spring of Blessing' },
  { transliteration: 'Aziz', meaning: 'The Honored One' },
  { transliteration: 'Baaligh', meaning: 'One of elevated rank' },
  { transliteration: 'Bar', meaning: 'Pious' },
  { transliteration: 'Basheer', meaning: 'Bringer of Good News' },
  { transliteration: 'Bayan', meaning: 'Clear speech' },
  { transliteration: 'Burhan', meaning: 'The Evidence' },
  { transliteration: 'Bushraa', meaning: 'Giver of glad tidings' },
  { transliteration: 'Daa', meaning: 'The Caller' },
  { transliteration: 'Daleel ul Khayraat', meaning: 'Guide to virtue' },
  { transliteration: 'Faateh', meaning: 'The Victor' },
  { transliteration: 'Faazil', meaning: 'Virtuous' },
  { transliteration: 'Faseehul Lisaan', meaning: 'Eloquent in speech' },
  { transliteration: 'Fatah', meaning: 'The Opener' },
  { transliteration: 'Ghani', meaning: 'Self-sufficient' },
  { transliteration: 'Gharib', meaning: 'The Stranger' },
  { transliteration: 'Ghaus', meaning: 'Helper in distress' },
  { transliteration: 'Ghays', meaning: 'Shower of mercy' },
  { transliteration: 'Ghiyaas', meaning: 'Full of succor' },
  { transliteration: 'Haad', meaning: 'The Guide' },
  { transliteration: 'Habeebullah', meaning: 'Beloved of Allah' },
  { transliteration: 'Habieb', meaning: 'The Beloved' },
  { transliteration: 'Hafeey', meaning: 'Most kind' },
  { transliteration: 'Hafiz', meaning: 'The Guardian' },
  { transliteration: 'Hakeem', meaning: 'The Wise' },
  { transliteration: 'Hamid', meaning: 'The Praiser' },
  { transliteration: 'Hamied', meaning: 'The Praiseworthy' },
  { transliteration: 'Haq', meaning: 'The Truth' },
  { transliteration: 'Harees-un-Alaikum', meaning: 'Concerned for believers' },
  { transliteration: 'Hashim', meaning: 'Crusher of evil' },
  { transliteration: 'Hashir', meaning: 'The Gatherer' },
  { transliteration: 'Hashmi', meaning: 'From Hashim clan' },
  { transliteration: 'Hidayatullah', meaning: 'Gift of Allah' },
  { transliteration: 'Hijazi', meaning: 'From Hijaz' },
  { transliteration: 'Hizbullah', meaning: 'Party of Allah' },
  { transliteration: 'Hudaa', meaning: 'Guidance' },
  { transliteration: 'Hujjat', meaning: 'The Proof' },
  { transliteration: 'Ikleel', meaning: 'Crown of Prophets' },
  { transliteration: 'Imam', meaning: 'Leader' },
  { transliteration: 'Imamul Muttaqeen', meaning: 'Leader of the pious' },
  { transliteration: 'Izzul Arab', meaning: 'Honor of the Arabs' },
  { transliteration: 'Jaami', meaning: 'Comprehensive' },
  { transliteration: 'Jabbar', meaning: 'Mighty' },
  { transliteration: 'Jawwad', meaning: 'Generous' },
  { transliteration: 'Kaaf', meaning: 'Sufficient' },
  { transliteration: 'Kaamil', meaning: 'Perfect' },
  { transliteration: 'Kaashiful Kurab', meaning: 'Reliever of hardships' },
  { transliteration: 'Kafeel', meaning: 'Guarantor' },
  { transliteration: 'Kaleemullah', meaning: 'One who converses with Allah' },
  { transliteration: 'Kareem', meaning: 'Noble' },
  { transliteration: 'Khaleel ur Rahman', meaning: 'Friend of the Most Merciful' },
  { transliteration: 'Khalil', meaning: 'True friend' },
  { transliteration: 'Khatamul Anbiya', meaning: 'Seal of the Prophets' },
  { transliteration: 'Khatamur Rusul', meaning: 'Seal of the Messengers' },
  { transliteration: 'Khateebul Umam', meaning: 'Orator for the nations' },
  { transliteration: 'Khatieb', meaning: 'Orator' },
  { transliteration: 'Khatim', meaning: 'Finalizer' },
  { transliteration: 'Maah', meaning: 'Eraser of disbelief' },
  { transliteration: 'Madani', meaning: 'Resident of Madinah' },
  { transliteration: 'Madoow', meaning: 'The Called One' },
  { transliteration: 'Mahd', meaning: 'The Guided' },
  { transliteration: 'Mahdee', meaning: 'Well Guided' },
  { transliteration: 'Mahdiy', meaning: 'The Guided One' },
  { transliteration: 'Mahmood', meaning: 'The Praised' },
  { transliteration: 'Makeen', meaning: 'Given rank' },
  { transliteration: 'Makeen II', meaning: 'Given rank' },
  { transliteration: 'Makhsoos bil Izz', meaning: 'Chosen for honor' },
  { transliteration: 'Makhsoos bil Majd', meaning: 'Chosen for glory' },
  { transliteration: 'Makhsoos bil Sharaf', meaning: 'Chosen for nobility' },
  { transliteration: 'Maloom', meaning: 'Known' },
  { transliteration: 'Mamoon', meaning: 'Secure' },
  { transliteration: 'Mansoor', meaning: 'Helped' },
  { transliteration: 'Maraj', meaning: 'Ascension' },
  { transliteration: 'Mashhood', meaning: 'Witnessed' },
  { transliteration: 'Mashkoor', meaning: 'Thankful' },
  { transliteration: 'Mateen', meaning: 'Strong' },
  { transliteration: 'Mawsool', meaning: 'Connected to Allah' },
  { transliteration: 'Miftaah', meaning: 'Key to secrets' },
];
