/** Roasty, light-hearted, Islam-focused lines shown when a blocked app is opened during salah. */
export const PRAYER_LOCK_DIALOGUES = [
  'Bro chose {appName} over salah? Shaytan is doing a victory lap.',
  'Your feed will still be there. Your prayer window will not.',
  '{appName} is not your imam. Stand up and pray.',
  'The algorithm wants your soul. WeDeen wants your sujood.',
  'Scrolling is temporary. Akhirah is… also temporary, but in a very different way. Pray now.',
  'You opened {appName} at salah time. Coincidence? Shaytan thinks not.',
  'That notification can wait. Allah\'s call cannot.',
  'Jannah does not have a "watch later" button. Neither should your salah.',
  'Your thumbs are fast on {appName}. Make them fast in prayer too.',
  'The dunya scrolls forever. This prayer window does not.',
  'Plot twist: the real treasure was the rak\'ah you almost skipped.',
  '{appName} will survive 5 minutes without you. Your iman might not survive skipping salah.',
  'Shaytan: "Just one more reel." Also Shaytan: "Skip salah." Classic combo.',
  'You were about to doom-scroll into the akhirah timeline. Go pray.',
  'Even your phone knows it\'s salah time. That\'s why {appName} is locked.',
  'The ummah is not built on streaks — it\'s built on salah. Go build.',
  'Your future self in Jannah is begging you to close {appName}.',
  'Hot take: salah > whatever {appName} is serving right now.',
  'The adhan already went. Your turn.',
  'You cannot like your way into Jannah. But you can pray your way closer.',
  '{appName} is halal entertainment. Missing salah still has consequences.',
  'Bro really said "one more video" at prayer time. Audacious.',
  'Allah gave you legs for sujood, not just for walking to your phone.',
  'The only thing that should go viral right now is your salah.',
  'Your soul downloaded an update: it\'s called Fajr/Dhuhr/Asr/Maghrib/Isha. Install it.',
  'Shaytan\'s favorite app during salah? Whatever you just tried to open.',
  'Shorter than a TikTok, more rewarding than a million views: one salah.',
  'The comment section can wait. The qiblah cannot.',
  'You were one tap away from distraction. Be one sajda away from peace.',
  'Close {appName}, open your heart. Salah is better than dunya — yes, even this dunya.',
  '{appName} can wait. Your Lord cannot.',
  'You\'re not missing out on {appName}. You\'re missing out on peace of mind.',
  'Pause the scroll. Start the salah.',
  '{appName} got you in 0.3 seconds. Salah takes 5 minutes. Do the math.',
  'This is your sign to put the phone down. We locked {appName} for you.',
  'Bro thought {appName} was urgent. Plot twist: the akhirah is.',
  'Your For You page will forgive you. Will you forgive yourself for skipping salah?',
  '{appName} is designed to steal your time. Give this moment back to Allah.',
  'One tap opened {appName}. One sajda opens doors in Jannah.',
  'The notifications on {appName} are not from Allah. This reminder is.',
  'You wouldn\'t ghost your mom. Don\'t ghost your Creator for {appName}.',
  '{appName} remembers your watch history. Allah remembers your salah. Choose wisely.',
  'Screen time on {appName}: high. Sujood time today: still pending.',
  'Habibi, close {appName}. Open your prayer mat.',
  'Trends on {appName} expire in 24 hours. Missed salah? Different kind of regret.',
  'You\'re one "I have prayed" away from freedom. {appName} offers no such button.',
  '{appName} has infinite content. You have finite time. Spend it on salah.',
  'Your eyes wanted {appName}. Your soul wanted sujood. Listen to your soul.',
  'Final boss of the day: not {appName}. It\'s your nafs. Go pray and win.',
  'Put {appName} on hold. Put your forehead on the ground.',
] as const;
