export const ACHIEVEMENT_IMAGES: Record<string, any> = {
  salah_1: require('../assets/images/achievments/row1col1.png'),
  salah_2: require('../assets/images/achievments/row1col2.png'),
  salah_3: require('../assets/images/achievments/row1col3.png'),
  salah_4: require('../assets/images/achievments/row1col4.png'),
  salah_5: require('../assets/images/achievments/row1col5.png'),
  salah_6: require('../assets/images/achievments/row1col6.png'),
  salah_7: require('../assets/images/achievments/row1col7.png'),
  salah_8: require('../assets/images/achievments/row1col8.png'),

  quran_1: require('../assets/images/achievments/row2col1.png'),
  quran_2: require('../assets/images/achievments/row2col2.png'),
  quran_3: require('../assets/images/achievments/row2col3.png'),
  quran_4: require('../assets/images/achievments/row2col4.png'),
  quran_5: require('../assets/images/achievments/row2col5.png'),
  quran_6: require('../assets/images/achievments/row2col6.png'),
  quran_7: require('../assets/images/achievments/row2col7.png'),
  quran_8: require('../assets/images/achievments/row2col8.png'),

  quran_9: require('../assets/images/achievments/row3col1.png'),
  quran_10: require('../assets/images/achievments/row3col2.png'),
  hafiz_1: require('../assets/images/achievments/row3col3.png'),
  hafiz_2: require('../assets/images/achievments/row3col4.png'),
  hafiz_3: require('../assets/images/achievments/row3col5.png'),
  hafiz_4: require('../assets/images/achievments/row3col6.png'),
  hafiz_5: require('../assets/images/achievments/row7col1.png'),
  hafiz_6: require('../assets/images/achievments/row7col2.png'),
  hafiz_7: require('../assets/images/achievments/row7col3.png'),
  hafiz_8: require('../assets/images/achievments/row7col4.png'),
  dhikr_1: require('../assets/images/achievments/row3col7.png'),
  dhikr_2: require('../assets/images/achievments/row3col8.png'),

  dhikr_3: require('../assets/images/achievments/row4col1.png'),
  dhikr_4: require('../assets/images/achievments/row4col2.png'),
  dhikr_5: require('../assets/images/achievments/row4col3.png'),
  dhikr_6: require('../assets/images/achievments/row4col4.png'),
  hadith_1: require('../assets/images/achievments/row4col5.png'),
  hadith_2: require('../assets/images/achievments/row4col6.png'),
  hadith_3: require('../assets/images/achievments/row4col7.png'),
  hadith_4: require('../assets/images/achievments/row4col8.png'),

  hadith_5: require('../assets/images/achievments/row5col1.png'),
  dev_1: require('../assets/images/achievments/row5col2.png'),
  dev_2: require('../assets/images/achievments/row5col3.png'),
  dev_3: require('../assets/images/achievments/row5col4.png'),
  dev_4: require('../assets/images/achievments/row5col5.png'),
  dev_5: require('../assets/images/achievments/row5col6.png'),
  dev_6: require('../assets/images/achievments/row5col7.png'),
  dev_7: require('../assets/images/achievments/row5col8.png'),
  dhikr_7: require('../assets/images/achievments/row4col4.png'),
  dev_8: require('../assets/images/achievments/row5col5.png'),
  dev_9: require('../assets/images/achievments/row6col1.png'),
  dev_10: require('../assets/images/achievments/row6col2.png'),
  dev_11: require('../assets/images/achievments/row6col3.png'),
  dev_12: require('../assets/images/achievments/row6col4.png'),
  dev_13: require('../assets/images/achievments/row6col5.png'),
  dev_14: require('../assets/images/achievments/row6col6.png'),
};

